### ISSUE TITLE
broken meds_etl_mimic in the main branch

### ISSUE THREAD

**Issue by mirmuss** [Medical-Event-Data-Standard/meds_etl#21] opened 2024-04-11 21:11 UTC
Hi,
I wanted to try speed gains from the cpp backend when I realized the following issue:
```
Processing tables into /nfs/home/mirmus/mimiciv_meds/temp
Processing icu/icustays
Processing icu/caregiver
Processing icu/d_items
Processing icu/datetimeevents
Processing icu/inputevents
Traceback (most recent call last):
  File "/nfs/home/mirmus/envs/femr/bin/meds_etl_mimic", line 8, in <module>
    sys.exit(main())
  File "/nfs/home/mirmus/envs/femr/lib/python3.10/site-packages/meds_etl/mimic/__init__.py", line 404, in main
    event_data = table_csv.select(**columns).collect()
  File "/nfs/home/mirmus/envs/femr/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1683, in collect
    return wrap_df(ldf.collect())
polars.exceptions.SchemaError: invalid series dtype: expected `String`, got `datetime[μs]`
``` 
I face this very same error regardless of the backend, when I install from main branch instead of pip
Am I missing something?

**Comment by EthanSteinberg** [comment] 2024-04-11 23:11
Thanks for the report!

I can reproduce this bug, and it looks like something I accidentally broke. Sorry about that! (We test on mimic-iv-demo, but this bug only triggers on the full mimic-iv unfortunately).

I have just fixed this and did a full mimic ETL to verify that it works. 

If you git pull you should be able to rerun.

I'll leave this issue open in case you run into further bugs.

**Comment by EthanSteinberg** [comment] 2024-04-12 14:35
> I face another error when using the duckdb backend:

@scottfleming It looks like your duckdb backend is malfunctioning? I'm going to remove the duckdb backend from the README then.

> However the cpp backend raised another error:

That's not an error, that's a warning that our code isn't 100% efficient. It would be good to make this more efficient though, which I guess I can do.

**Comment by EthanSteinberg** [comment] 2024-05-11 11:36
@mirmuss Did everything work for you? I think I'm going to close this issue in the meantime, but feel free to reopen if you run into further issues.

**Closed by EthanSteinberg** 2024-05-11 11:36 UTC
